### ISSUE TITLE
Unnecessary calls in BlockBuffer::getFreeBlock()

### ISSUE THREAD

**Issue by SaintNerevar** [Nitcbase/nitcbase.github.io#20]
Block type is already set when setting the header using setHeader(). There is no need to call setBlockType again.
setHeader() also calls getBufferPtr() which in turn calls getBlock() which calls getFreeBuffer() (everytime since the block number corresponds to an unallocated block) which makes calling getFreeBuffer() in getFreeBlock() unnecessary.

**Comment by gokulsreekumar** [comment]
* setHeader() and setBlockType() is being modified for issue #22
