### ISSUE TITLE
BlockBuffer::setHeader must set the Block Type in the Block Allocation Map

### ISSUE THREAD

**Issue by SaintNerevar** [Nitcbase/nitcbase.github.io#22]
Since setHeader actually modifies the block type of the block being set, it's also its responsibility to set the correct block type in the Block Allocation Map.

**Comment by jessiyajoy** [comment]
According to the existing design,
- setBlockType sets the block type in Block Allocation Map
- setHeader sets the block type in block header

This should be changed such that whenever block type needs to be updated, it should be updated in both block header and Block Allocation Map.
setHeader and setBlockType needs to be changed accordingly.

**Comment by gokulsreekumar** [comment]
Solutions possible:
1. setBlockType() should update Block Allocation Map AND Block Header field. setHeader() can call setBlockType() to set type. For other header fields it can do the update itself.
2. setHeader() does current setHeader function, in addition to which it calls setBlockType

**Comment by clifordjoshy** [comment]
A block once allocated should not be allowed to change it's type. It should be freed and reallocated. I'll mention in the caution section for the function that the block type is not expected to be changed at runtime

**Comment by clifordjoshy** [comment]
Additionally, the `getBlockType()` is never used. Removing it from the spec

**Comment by clifordjoshy** [comment]
`setBlockType()` does not need to be exposed outside the Buffer Layer. Making it protected
