### ISSUE TITLE
Calling getBlock in BlockBuffer constructor 2 is unnecessary

### ISSUE THREAD

**Issue by SaintNerevar** [Nitcbase/nitcbase.github.io#23]
The design stipulates that any get/set methods accessing disk blocks must call BlockBuffer::getBufferPtr() which calls getBlock(). So, not calling getBlock() in the constructor simply delays copying the block into the buffer until it is actually needed i.e to access the blocks data.

**Comment by gokulsreekumar** [comment]
- `getBlock()` removed and `loadBlockAndGetBufferPtr()` function introduced
