### ISSUE TITLE
BlockBuffer::getFreeBlock Error Handling, Constructor 1 Issue, DISK_FULL issue

### ISSUE THREAD

**Issue by jessiyajoy** [Nitcbase/nitcbase.github.io#33]
- Block type is already set when setting the header using setHeader(). There is no need to call setBlockType again.
- setHeader() also calls getBufferPtr() which in turn calls getBlock() which calls getFreeBuffer() (everytime since the block number corresponds to an unallocated block) which makes calling getFreeBuffer() in getFreeBlock() unnecessary.

**Comment by gokulsreekumar** [comment]
* BlockBuffer::getFreeBlock is called only in BlockBuffer::constructor1
As such, the code in getFreeBlock can be moved entirely into the constructor1 and getFreeBlock can be scrapped.

**Comment by SaintNerevar** [comment]
The second point in [](url)

> * Block type is already set when setting the header using setHeader(). There is no need to call setBlockType again.
> * setHeader() also calls getBufferPtr() which in turn calls getBlock() which calls getFreeBuffer() (everytime since the block number corresponds to an unallocated block) which makes calling getFreeBuffer() in getFreeBlock() unnecessary.

is probably confusing.

The idea is that getFreeBlock() sets the header of the newly allocated (not yet buffered) block. This results in a call to getFreeBuffer() everytime. That's why calling getFreeBuffer() in getFreeBlock() is unnecessary

**Comment by gokulsreekumar** [comment]
- Update for Constructor - 2 has been done: which includes creating a new function called loadBlockAndGetBufferPtr() method
- Change that remains is DISK_FULL issue which can happen in Constructor - 1

**Comment by jessiyajoy** [comment]
```
// Constructor 1
BlockBuffer::BlockBuffer(char blockType) {
	// allocate a block on the disc and a buffer in memory to hold the new block of given type using getFreeBlock function.
	int newBlockNum;

	switch (blockType) {
		case 'R':
			newBlockNum = getFreeBlock(REC);
			break;
		case 'I':
			newBlockNum = getFreeBlock(IND_INTERNAL);
			break;
		case 'L':
			newBlockNum = getFreeBlock(IND_LEAF);
			break;
		default:
			newBlockNum = FAILURE;
	}

	// set the blockNum field of the object to that of the allocated block number.
	// TODO: what happens if disk full..note down
	this->blockNum = newBlockNum;
}
```

**Comment by gokulsreekumar** [comment]
**Done**

**Comment by clifordjoshy** [comment]
verified that the caller handles E_DISKFULL wherever the constructor is in use.
