### ISSUE TITLE
Update Physical Layer docs to have catalog attribute names consistent with their names in Disk

### ISSUE THREAD

**Issue by SaintNerevar** [Nitcbase/nitcbase.github.io#41]
For Ex. The attribute `RelationName` in the docs is actually named `RelName` in the Disk.
This consistency is needed because BlockAccess methods ask for attribute names to search for records.

**Comment by SaintNerevar** [comment]
Also, names of the catalogs i.e `ATTRIBUTECAT` and `RELATIONCAT` should be mentioned in the documentation. These are the names that should be used in OpenRelTable constructor as instead of `AttrCatalog` and `RelCatalog`

**Comment by gokulsreekumar** [comment]
Done
