### ISSUE TITLE
Issues with BlockAccess::ba_deleteRelation()

### ISSUE THREAD

**Issue by SaintNerevar** [Nitcbase/nitcbase.github.io#45]
A few modifications

- It is not necessary to return the return values from getHeader, setHeader, etc as we discussed in the last meeting. We just return only the relevant error codes
- Change the for loop to a while loop
- `lastBlk` in the relation catalog entry for the attribute catalog must be made consistent in the case `numEntries` becomes 0 and the block currently being released is the last block
- The loop that deletes the attributes must count the attributes as it deletes them. This count must be subtracted from the RelCache entry for Attribute Catalog instead of the whole number of Attributes (This is useful in the case of partial creation of a relation)
- The above point nullifies the need for holding the actual number of attributes in a variable

**Comment by gokulsreekumar** [comment]
Done, **Except the second last point** which requires some additional testing.

**Comment by gokulsreekumar** [comment]
For the second last point the following change has been done in the documentation:
- added the following: `int numberOfAttributesDeleted = 0;` before the loop that deletes the attribute catalog entries
- Inside the loop the following update is done right after the check if iteration over all attrs is done or not: `numberOfAttributesDeleted++;`
- did the following for the update of RelCache's Entry corresponding to Attribute Catalog: 
```cpp
/** Update attribute catalog entry (number of records in attribute catalog is decreased by numberOfAttributesDeleted) **/
	i.e., #Records = #Records - numberOfAttributesDeleted
```

**Comment by SaintNerevar** [comment]
All good!
