### ISSUE TITLE
renameAttr/renameRel in Schema layer do not check for E_INVALID

### ISSUE THREAD

**Issue by SaintNerevar** [Nitcbase/nitcbase.github.io#46]
A check for E_INVALID must be included before the check for E_RELOPEN since the catalogs are always open.

**Comment by gokulsreekumar** [comment]
**Done**
- The error code is changed from `E_INVALID` to `E_NOTPERMITTED`
- The same check added to all methods in Schema wherever relavant.
   - `deleteRel`, `createIndex`, `dropIndex`, `renameRel`, `renameAttr`, `closeRel`

**Comment by SaintNerevar** [comment]
All good!
