### ISSUE TITLE
Setting UP CLion Dev Environment for Debugging

### ISSUE THREAD

**Issue by gokulsreekumar** [Nitcbase/nitcbase.github.io#7]
Instructions for setting up a CLion Development Environment:

TO BE WRITTEN

1. Install CLION
2. Complete the Above steps and ensure `NITCbase/` directory is present
3. Press `Open` Button and inside the files navigator, choose `/NITCbase/` directory from inside WSL and press `OK`.
   * The directory would be present in the following folder: `\\wsl$\Ubuntu\home\<your username>\`, if you ran the 3rd step above from the $HOME directory of WSL Ubuntu Linux. 
4. Go to `File` menu, choose settings, and then choose `Build, Execution, Deployment` from the sidebar.
5. Select the `Toolchans` menu and then press the `+` button followed by `WSL` option from the Dropdown menu.
6. Select the Cmake and versions of C and C++

**Comment by jessiyajoy** [comment]
will see later
